services:
  db:
    image: postgres:13
    env_file:
      - environment/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rag_network

  minio:
    image: minio/minio:latest
    env_file:
      - environment/.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - rag_network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag_network


  auth:
    build:
      dockerfile: ./Dockerfile
      context: ./backend/auth
    env_file:
      - environment/.env
    depends_on:
      - db
    ports:
      - "8002:8002"
    networks:
      - rag_network

  file_core:
    build:
      dockerfile: ./Dockerfile
      context: ./backend/file_checker
    env_file:
      - environment/.env
    depends_on:
      - db
      - minio
      - core
    ports:
      - "8003:8003"
    networks:
      - rag_network

  core:
    build:
      dockerfile: ./Dockerfile
      context: ./backend/core
    env_file:
      - environment/.env
    depends_on:
      - db
      - minio
      - qdrant
    ports:
      - "8005:8005"
    networks:
      - rag_network

  gateway:
    build:
      dockerfile: ./Dockerfile
      context: ./backend/gateway
    env_file:
      - environment/.env
    depends_on:
      - auth
      - file_core
    ports:
      - "8001:8001"
    networks:
      - rag_network
  
  ui:
    build:
      context: ./client/ui
      dockerfile: Dockerfile
      args:
        - VITE_APPLICATION_MODE=dev
        - VITE_API_BASE_URL=http://localhost
    container_name: frontend_app
    env_file:
      - environment/.env
    command: npm run build
    volumes:
      - ./client/ui:/app
      - /app/node_modules
    depends_on:
      - core
    networks:
      - rag_network

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/ui/dist:/usr/share/nginx/html
      - ./environment/certificate.key:/etc/nginx/certificate.key:ro
      - ./environment/server.crt:/etc/nginx/server.crt:ro
    networks:
      - rag_network


volumes:
  db_data:
  minio_data:
  qdrant_data:

networks:
  rag_network:
    driver: bridge